# Generated by Django 4.2.21 on 2026-01-01 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_idempotency_key_orderitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_webhook_events', to='orders.order')),
            ],
        ),
    ]
