# Generated by Django 4.2.21 on 2025-01-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_order_gift_message_order_is_gift"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="preferred_delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
