# Generated by Django 4.2.21 on 2026-01-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publish_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unpublish_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
